# Generated by Django 4.0.4 on 2022-05-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='type',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
